### ISSUE TITLE
How to setup batch_size?

### ISSUE THREAD

**Issue by shakacs** [hycis/Mozi#3]
There seems no where to set batch_size, as neither datablock nor singleblock class have an input entry for it.

**Comment by hycis** [comment]
Singleblock and datablock is a subclass of dataset so you can just put batch_size as argument to set batch_size
https://github.com/hycis/Mozi/blob/master/example/datablocks_example.py#L62 <https://github.com/hycis/Mozi/blob/master/example/datablocks_example.py#L62>

**Comment by shakacs** [comment]
Thanks. The reason i post this issue is that when i tried to run the code in tourist, it throws "'Mnist' object has no attribute 'batch_size'", the same exception thrown once i tried to print the batch_size of a datablock object, and i traced into the source and found that only IterMatrix class has a member called batch_size. May be i got something wrong.

**Comment by hycis** [comment]
Yap, the dataset object itself contains the train, valid and test itermatrix, and dataset itself indeed does not have the attribute of batch_size. However you can call the batch_size by looking into the itermatrix, for example

dataset = Mnist(batch_size=32)
print(dataset.train.batch_size)
